server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pd_store?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Syp950628

  rabbitmq:
    host: 192.168.64.140
    port: 5672
    # virtualHost: /pd
    username: admin
    password: admin




mybatis:
  #typeAliasesPackage: cn.tedu.ssm.pojo
  mapperLocations: classpath:com.pd.mapper/*.xml

logging:
  level:
    cn.tedu.ssm.mapper: debug
resources: # 指定静态资源的路径
  static-locations: classpath:/
  cache-period: 0